"use strict";

// Tailwind config: https://tailwindcss.com/docs/configuration
module.exports = {
  future: {
    purgeLayersByDefault: true,
    removeDeprecatedGapUtilities: true,
  },
  purge: {
    content: [
      "./src/**/*.js",
      "./src/**/*.jsx",
      "./src/**/*.md",
      "./src/**/*.mdx",
      "./src/**/*.ts",
      "./src/**/*.tsx",
    ],
    options: {
      whitelist: ["a", "active", "body", "html", "img"],
    },
  },
  theme: {
    colors: {
      background: {
        default: "var(--color-background)",
        paper: "var(--color-background-paper)",
        primary: "var(--color-background-primary)",
        secondary: "var(--color-background-secondary)",
      },
      black: "var(--color-black)",
      copy: {
        default: "var(--color-copy)",
        paper: "var(--color-copy-paper)",
        primary: "var(--color-copy-primary)",
        "primary-dark": "var(--color-copy-primary-dark)",
        "primary-light": "var(--color-copy-primary-light)",
        secondary: "var(--color-copy-secondary)",
        "secondary-dark": "var(--color-copy-secondary-dark)",
        "secondary-light": "var(--color-copy-secondary-light)",
      },
      gray: {
        50: "var(--color-gray-50)",
        100: "var(--color-gray-100)",
        200: "var(--color-gray-200)",
        300: "var(--color-gray-300)",
        400: "var(--color-gray-400)",
        500: "var(--color-gray-500)",
        600: "var(--color-gray-600)",
        700: "var(--color-gray-700)",
        800: "var(--color-gray-800)",
        900: "var(--color-gray-900)",
      },
      primary: {
        100: "var(--color-primary-100)",
        200: "var(--color-primary-200)",
        300: "var(--color-primary-300)",
        400: "var(--color-primary-400)",
        500: "var(--color-primary-500)",
        600: "var(--color-primary-600)",
        700: "var(--color-primary-700)",
        800: "var(--color-primary-800)",
        900: "var(--color-primary-900)",
      },
      purple: {
        100: "var(--color-purple-100)",
        200: "var(--color-purple-200)",
        300: "var(--color-purple-300)",
        400: "var(--color-purple-400)",
        500: "var(--color-purple-500)",
        600: "var(--color-purple-600)",
        700: "var(--color-purple-700)",
        800: "var(--color-purple-800)",
        900: "var(--color-purple-900)",
      },
      secondary: {
        100: "var(--color-secondary-100)",
        200: "var(--color-secondary-200)",
        300: "var(--color-secondary-300)",
        400: "var(--color-secondary-400)",
        500: "var(--color-secondary-500)",
        600: "var(--color-secondary-600)",
        700: "var(--color-secondary-700)",
        800: "var(--color-secondary-800)",
        900: "var(--color-secondary-900)",
      },
      service: {
        fail: "var(--color-service-fail)",
        info: "var(--color-service-info)",
        pass: "var(--color-service-pass)",
        warn: "var(--color-service-warn)",
      },
      white: "var(--color-white)",
      yellow: {
        100: "var(--color-yellow-100)",
        200: "var(--color-yellow-200)",
        300: "var(--color-yellow-300)",
        400: "var(--color-yellow-400)",
        500: "var(--color-yellow-500)",
        600: "var(--color-yellow-600)",
        700: "var(--color-yellow-700)",
        800: "var(--color-yellow-800)",
        900: "var(--color-yellow-900)",
      },
    },
    container: {
      center: true,
      padding: {
        default: "1rem",
        sm: "1.5rem",
        md: "3rem",
        lg: "6rem",
        xl: "12rem",
      },
    },
    extend: {
      listStyleType: {
        square: "square",
      },
    },
    fontFamily: {
      sans: [
        "Nunito Sans",
        "Roboto",
        "-apple-system",
        "BlinkMacSystemFont",
        "'Segoe UI'",
        "'Helvetica Neue'",
        "Arial",
        "'Noto Sans'",
        "sans-serif",
        "'Apple Color Emoji'",
        "'Segoe UI Emoji'",
        "'Segoe UI Symbol'",
        "'Noto Color Emoji'",
      ],
      serif: ["Georgia", "Cambria", "'Times New Roman'", "Times", "serif"],
      mono: [
        "Menlo",
        "Monaco",
        "Consolas",
        "'Liberation Mono'",
        "'Courier New'",
        "monospace",
      ],
    },
    screens: {
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
    },
  },
  variants: {},
  plugins: [],
};
