"use strict";

// Tailwind config: https://tailwindcss.com/docs/configuration

module.exports = {
  darkMode: "class",
  future: {
    applyComplexClasses: true,
    purgeLayersByDefault: true,
    removeDeprecatedGapUtilities: true,
  },
  purge: {
    content: [
      "./src/**/*.js",
      "./src/**/*.jsx",
      "./src/**/*.md",
      "./src/**/*.mdx",
      "./src/**/*.ts",
      "./src/**/*.tsx",
    ],
  },
  theme: {
    backgroundColor: (theme) => ({
      ...theme("colors"),
      default: "var(--color-background)",
      hover: "var(--color-background-hover)",
      paper: "var(--color-background-paper)",
      primary: "var(--color-background-primary)",
      "primary-hover": "var(--color-background-primary-hover)",
      "primary-dark": "var(--color-background-primary-dark)",
      "primary-dark-hover": "var(--color-background-primary-dark-hover)",
      "primary-light": "var(--color-background-primary-light)",
      "primary-light-hover": "var(--color-background-primary-light-hover)",
      secondary: "var(--color-background-secondary)",
      "secondary-hover": "var(--color-background-secondary-hover)",
      "secondary-dark": "var(--color-background-secondary-dark)",
      "secondary-dark-hover": "var(--color-background-secondary-dark-hover)",
      "secondary-light": "var(--color-background-secondary-light)",
      "secondary-light-hover": "var(--color-background-secondary-light-hover)",
    }),
    borderColor: (theme) => ({
      ...theme("colors"),
      default: "var(--color-background-secondary)",
      hover: "var(--color-background-hover)",
      paper: "var(--color-text-paper)",
      primary: "var(--color-background-primary)",
      "primary-hover": "var(--color-background-primary-hover)",
      "primary-dark": "var(--color-background-primary-dark)",
      "primary-dark-hover": "var(--color-background-primary-dark-hover)",
      "primary-light": "var(--color-background-primary-light)",
      "primary-light-hover": "var(--color-background-primary-light-hover)",
      secondary: "var(--color-background-secondary)",
      "secondary-hover": "var(--color-background-secondary-hover)",
      "secondary-dark": "var(--color-background-secondary-dark)",
      "secondary-dark-hover": "var(--color-background-secondary-dark-hover)",
      "secondary-light": "var(--color-background-secondary-light)",
      "secondary-light-hover": "var(--color-background-secondary-light-hover)",
    }),
    textColor: (theme) => ({
      ...theme("colors"),
      contrast: "var(--color-background-paper)",
      "contrast-hover": "var(--color-background-hover)",
      "contrast-paper": "var(--color-text-paper)",
      "contrast-primary": "var(--color-background-primary)",
      "contrast-primary-hover": "var(--color-background-primary-hover)",
      "contrast-primary-dark": "var(--color-background-primary-dark)",
      "contrast-primary-dark-hover":
        "var(--color-background-primary-dark-hover)",
      "contrast-primary-light": "var(--color-background-primary-light)",
      "contrast-primary-light-hover":
        "var(--color-background-primary-light-hover)",
      "contrast-secondary": "var(--color-background-secondary)",
      "contrast-secondary-hover": "var(--color-background-secondary-hover)",
      "contrast-secondary-dark": "var(--color-background-secondary-dark)",
      "contrast-secondary-dark-hover":
        "var(--color-background-secondary-dark-hover)",
      "contrast-secondary-light": "var(--color-background-secondary-light)",
      "contrast-secondary-light-hover":
        "var(--color-background-secondary-light-hover)",
      default: "var(--color-text)",
      hover: "var(--color-text-hover)",
      paper: "var(--color-text-paper)",
    }),
    colors: {
      black: "var(--color-black)",
      gray: {
        50: "var(--color-gray-50)",
        100: "var(--color-gray-100)",
        200: "var(--color-gray-200)",
        300: "var(--color-gray-300)",
        400: "var(--color-gray-400)",
        500: "var(--color-gray-500)",
        600: "var(--color-gray-600)",
        700: "var(--color-gray-700)",
        800: "var(--color-gray-800)",
        900: "var(--color-gray-900)",
      },
      primary: {
        100: "var(--color-primary-100)",
        200: "var(--color-primary-200)",
        300: "var(--color-primary-300)",
        400: "var(--color-primary-400)",
        500: "var(--color-primary-500)",
        600: "var(--color-primary-600)",
        700: "var(--color-primary-700)",
        800: "var(--color-primary-800)",
        900: "var(--color-primary-900)",
      },
      purple: {
        100: "var(--color-purple-100)",
        200: "var(--color-purple-200)",
        300: "var(--color-purple-300)",
        400: "var(--color-purple-400)",
        500: "var(--color-purple-500)",
        600: "var(--color-purple-600)",
        700: "var(--color-purple-700)",
        800: "var(--color-purple-800)",
        900: "var(--color-purple-900)",
      },
      secondary: {
        100: "var(--color-secondary-100)",
        200: "var(--color-secondary-200)",
        300: "var(--color-secondary-300)",
        400: "var(--color-secondary-400)",
        500: "var(--color-secondary-500)",
        600: "var(--color-secondary-600)",
        700: "var(--color-secondary-700)",
        800: "var(--color-secondary-800)",
        900: "var(--color-secondary-900)",
      },
      service: {
        fail: "var(--color-service-fail)",
        info: "var(--color-service-info)",
        pass: "var(--color-service-pass)",
        warn: "var(--color-service-warn)",
      },
      white: "var(--color-white)",
      yellow: {
        100: "var(--color-yellow-100)",
        200: "var(--color-yellow-200)",
        300: "var(--color-yellow-300)",
        400: "var(--color-yellow-400)",
        500: "var(--color-yellow-500)",
        600: "var(--color-yellow-600)",
        700: "var(--color-yellow-700)",
        800: "var(--color-yellow-800)",
        900: "var(--color-yellow-900)",
      },
    },
    container: {
      center: true,
      padding: {
        DEFAULT: "1rem",
        sm: "1.25rem",
        md: "1.5rem",
        lg: "4rem",
        xl: "6rem",
      },
    },
    extend: {
      borderWidth: {
        3: "3px",
        5: "5px",
        6: "6px",
        7: "7px",
      },
      flex: {
        full: "1 100%",
      },
      fontSize: {
        "7xl": "5rem",
      },
      listStyleType: {
        square: "square",
      },
      height: {
        "screen-1/4": "25vh",
        "screen-1/3": "33.333333vh",
        "screen-1/2": "50vh",
        "screen-2/3": "66.666667vh",
        "screen-3/4": "75vh",
      },
      inset: {
        "1/4": "25%",
        "1/3": "33.3333%",
        "1/2": "50%",
        "2/3": "66.6666%",
        "3/4": "75%",
        full: "100%",
      },
      maxWidth: {
        "screen-1/4": "25vw",
        "screen-1/3": "33.333333vw",
        "screen-1/2": "50vw",
        "screen-2/3": "66.666667vw",
        "screen-3/4": "75vw",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
        7: "1.75rem",
        9: "2.25rem",
        11: "2.75rem",
        13: "3.25rem",
        14: "3.5rem",
        15: "3.75rem",
        17: "4.25rem",
        18: "4.5rem",
        19: "4.75rem",
        21: "5.25rem",
        22: "5.5rem",
        23: "5.75rem",
        25: "6.25rem",
        26: "6.5rem",
        27: "6.75rem",
        100: "30rem",
        "vh-1/4": "25vh",
        "vh-1/3": "33.333333vh",
        "vh-1/2": "50vh",
        "vh-2/3": "66.666667vh",
        "vh-3/4": "75vh",
        "vw-1/4": "25vw",
        "vw-1/3": "33.333333vw",
        "vw-1/2": "50vw",
        "vw-2/3": "66.666667vw",
        "vw-3/4": "75vw",
        "vw-full": "100vw",
      },
      width: {
        "1/4": "25%",
        "1/3": "33.3333%",
        "1/2": "50%",
        "2/3": "66.6666%",
        "3/4": "75%",
        auto: "auto",
        "screen-1/4": "25vw",
        "screen-1/3": "33.3333vw",
        "screen-1/2": "50vw",
        "screen-2/3": "66.6666vw",
        "screen-3/4": "75vw",
      },
    },
    fontFamily: {
      sans: [
        "Nunito Sans",
        "Roboto",
        "-apple-system",
        "BlinkMacSystemFont",
        "'Segoe UI'",
        "'Helvetica Neue'",
        "Arial",
        "'Noto Sans'",
        "sans-serif",
        "'Apple Color Emoji'",
        "'Segoe UI Emoji'",
        "'Segoe UI Symbol'",
        "'Noto Color Emoji'",
      ],
      serif: ["Georgia", "Cambria", "'Times New Roman'", "Times", "serif"],
      mono: [
        "Menlo",
        "Monaco",
        "Consolas",
        "'Liberation Mono'",
        "'Courier New'",
        "monospace",
      ],
    },
    minHeight: {
      0: "0px",
      "1/4": "25%",
      "1/3": "33.333333%",
      "1/2": "50%",
      "2/3": "66.666667%",
      "3/4": "75%",
      full: "100%",
      "screen-1/4": "25vh",
      "screen-1/3": "33.333333vh",
      "screen-1/2": "50vh",
      "screen-2/3": "66.666667vh",
      "screen-3/4": "75vh",
      screen: "100vh",
    },
    screens: {
      xs: "480px",
      sm: "640px",
      md: "768px",
      lg: "1024px",
      xl: "1280px",
    },
  },
};
